### ISSUE TITLE
Frage 

### ISSUE THREAD

**Issue by renja-g** [MaxiAmZocken/My-Stuff#1]
Ich kenne mich noch nicht so gut mit AutoHotKey aus,
und wollte fragen ob du mir vielleicht helfen möchtest.

**Comment by MaximilianSteimar** [comment]
wie kann ich dir denn helfen ?

**Comment by Ayato-hub** [comment]
> wie kann ich dir denn helfen ?

Ich möchte ein Script erstellen das jedes Mal, wenn eine Runde vorbei ist die % Anzahl in ein Excel Tabelle schreibt.

Der Screen würde so aussehen: [](https://imgur.com/a/ZkFnuFa)
Das was ich brauche ist nur die % zahl: [](https://imgur.com/L9ekKwk)

Ist das möglich?

**Comment by renja-g** [comment]
Ich möchte ein Script erstellen das jedes Mal, wenn eine Runde vorbei ist
die % Anzahl in ein Excel Tabelle schreibt.

Der Screen würde so aussehen: https://imgur.com/a/ZkFnuFa
Das was ich brauche ist nur die % zahl: https://imgur.com/L9ekKwk

Ist das möglich?


Sorry, ich war mir nicht sicher wie ich antworten sollte

Am So., 21. Feb. 2021 um 14:09 Uhr schrieb Maxi <notifications@github.com>:

**Comment by MaximilianSteimar** [comment]
meines wissen nach ist sowas nicht möglich, weil ich noch nie etwas von einem "screen reader" bei autohotkey gehört habe, aber du kannst ja auf dem ahk subreddit (https://www.reddit.com/r/AutoHotkey/) nach einer lösung fragen, da gibt es meistens sehr gute antworten
